version: "3.8"
services:
  postgres:
    image: "postgres:12.5"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres:
